Templates page for site
formester/formester-site pull request #85
Opened 2023-01-20 13:32 UTC by anirudh-tantry

2023-01-23 12:52 UTC, ankitsinghaniyaz approved these changes

2023-01-23 12:52 UTC, ankitsinghaniyaz commented on layouts/default.vue
> +  },
let's create a new layout, that's a better architecture and let's use that on templates page

2023-01-23 12:52 UTC, ankitsinghaniyaz commented on pages/templates/_slug.vue
> +      window.location.href = `https://app.formester.com/forms/new?template_id=${id}`
let's open this in new tab

2023-01-30 13:27 UTC, ankitsinghaniyaz requested changes

2023-01-30 13:27 UTC, ankitsinghaniyaz commented on pages/templates/index.vue
> +          'Use our Formester form templates including surveys, reviews, registrations, & more for any industry! Automate workflows with online templates.',
nice touch 👍

2023-01-30 13:27 UTC, ankitsinghaniyaz commented on pages/templates/category/_slug.vue
> +      title: 'Templates | Formester',
but you missed this one?? 

Should instead show the category name here

``` `${category.name} Templates | Formester` ```

2023-01-30 13:27 UTC, ankitsinghaniyaz commented on pages/templates/_slug.vue
> +        description: this.template?.description,
should also have a default description which would work with the title incase the description is not coming

2023-01-31 08:25 UTC, anirudh-tantry commented on pages/templates/category/_slug.vue
> +          'Use our Formester form templates including surveys, reviews, registrations, & more for any industry! Automate workflows with online templates.',
any suggestion for this?

2023-01-31 08:50 UTC, ankitsinghaniyaz approved these changes

2023-01-31 10:15 UTC, merged